apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-game-systems

resources:
    - ../../base
    - atlas-db-user.yaml
    - configmaps.yaml
    - externalsecret-nats.yaml
    - ingress.yaml
    - middlewares.yaml
    - secrets/db.yaml

patches:
    - path: deployment-nats.yaml
      target:
          kind: Deployment
          name: api-v1

labels:
    - pairs:
          app.kubernetes.io/name: game-systems-api
          app.kubernetes.io/version: v1
          app.kubernetes.io/component: api
          app.kubernetes.io/part-of: game-systems
          com.sweetrpg/env: dev
      includeSelectors: false
      includeTemplates: true

generatorOptions:
    disableNameSuffixHash: true
