apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-gamesystems

resources:
    - ../../base
    - atlas-db-user.yaml
    - configmaps.yaml
    - ingress.yaml
    - middlewares.yaml
    - secrets/db.yaml

labels:
    - pairs:
          app: api
          version: v1
          platform: sweetrpg
          package: gamesystems
          component: api

generatorOptions:
    disableNameSuffixHash: true
