apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sweetrpg-gamesystems

resources:
    - ../../base
    - configmaps.yaml
    - secrets.yaml
    - ingress.yaml
    - middlewares.yaml

labels:
    - pairs:
          app: api
          version: v1
          platform: sweetrpg
          package: gamesystems
          component: api

generatorOptions:
    disableNameSuffixHash: true

images:
    - name: gamesystems-api
      newName: ghcr.io/sweetrpg/gamesystems-api
      newTag: latest
